#!/bin/bash
#!/bin/bash

# Define color codes
R="\e[31m"
N="\e[0m"

# Declare and initialize variables
num1=10
num2=20

# Calculate the sum and sub
sum=$((num1 + num2))
sub=$((num1 - num2))

# Print the results with the sum and sub in red
echo -e "Sum: {$R}{$sum}{$N}"
echo -e "Sub: {$R}{$sub}{$N}"
