#!/bin/bash

# Variables
AMI_ID=ami-0b4f379183e5706b9
SG_ID=sg-0463541756967fe45
INSTANCES=("mongodb" "redis" "mysql" "rabbitmq" "catalogue" "user" "cart" "shipping" "payment" "dispatch" "web")
availability_zone="us-east-1a"

for i in "${INSTANCES[@]}"
do
    echo "instance is: $i"
    if [ $i == "mongodb" ] || [ $i == "mysql" ] || [ $i == "shipping" ]
    then
    INSTANCE_TYPE="t3.medium"
    else
    INSTANCE_TYPE="t2.micro"
fi

# Create EC2 instance
aws ec2 run-instances --image-id ami-0b4f379183e5706b9 --instance-type $INSTANCE_TYPE  --security-group-ids sg-0463541756967fe45 --placement "AvailabilityZone=$availability_zone"
done 
