#!/bin/bash

id=$(id -u)

validate(){
    if [$? -ne 0]
then
    echo "Error: installing failed"
    exit 1
else
   echo " installing success"
   fi
}

if [$id -ne 0]
then
    echo "Error: please run the script with root access"
else
    echo " you are root user"
fi 

yum install mysql -y
validate
yum install git -y
validate