#!/bin/bash

id=$(id -u)

if [$id -ne 0]
then
    echo "Error: please run the script with root access"
else
    echo " you are root user"
fi 

yum install mysql -y

if [$? -ne 0]
then
    echo "Error: installing mysql is failed"
else
   echo " installing mysql success"
   fi

yum install git -y

if [$? -ne 0]
then
    echo "Error: installing git is failed"
else
   echo " installing git success"
   fi