#!/bin/bash

id=$(id -u)

if [$? -ne 0]
then
    echo -e "$R Error: please run the script with root access $N"
    exit 1
else
   echo " you are the root user"
   fi

   echo " all arguments are passed: $@"