#!/bin/bash

id=$(id -u)

if [$id -ne 0]
then
    echo "Error: please run the script with root access"
else
    echo " you are root user"
fi 

yum install mysql -y

if [$? -ne 0]
then
    echo "Error: installing mysql is failed"
else
   echo " installing my success"
   fi