#!/bin/bash

id=$(id -u)
echo "script name: $0"
validate(){
    if [$1 -ne 0]
then
    echo "Error: $2.... failed"
    exit 1
else
   echo " $2.... success"
   fi
}
if [$id -ne 0]
then
    echo "Error: please run the script with root access"
    exit 1
else
    echo " you are root user"
fi 
yum install mysql -y
validate $? " installing mysql"
yum install git -y
validate $? " installing git"