#!/bin/bash
person1=sagar
person2=pradeep

echo "$person1: hi $person2, gm"
echo "$person2: hi $person1, gm"
echo "$person1: how are you $person2"
echo "$person2: im good tq, what about you"
echo "$person1: im fine tq"